# Generated by Django 4.1.3 on 2022-11-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
