# Generated by Django 4.1.3 on 2022-11-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
