# Generated by Django 4.1.3 on 2022-12-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
