# Generated by Django 4.1.3 on 2022-12-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_post_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
