# Generated by Django 4.1.3 on 2022-12-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
        ('main', '0014_post_date'),
    ]

    operations = [
    ]
